from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
BANK=(ROOT/"profitos"/"routes"/"bank_sync.py").read_text(encoding="utf-8")
ACC=(ROOT/"profitos"/"accounting.py").read_text(encoding="utf-8")

def _fn(src, name, next_name):
    return src.split(f"def {name}",1)[1].split(f"def {next_name}",1)[0]

def test_v372_customer_reconciliation_creates_individual_balanced_bank_entry():
    b=_fn(ACC,"generate_sale_partial_payment_entry","generate_purchase_entry")
    assert "source_type = 'outgoing_invoice_payment_v2'" in b
    assert "'512000', 'debit': amount" in b
    assert "'411000', 'credit': amount" in b
    assert "_entry_already_exists(conn, source_type, payment['id'], entity_id)" in b

def test_v372_supplier_reconciliation_creates_individual_balanced_bank_entry():
    b=_fn(ACC,"generate_purchase_partial_payment_entry","seed_accounting_defaults")
    assert "source_type = 'purchase_invoice_payment_v2'" in b
    assert "'401000','debit':amount" in b
    assert "'512000','credit':amount" in b
    assert "_entry_already_exists(conn, source_type, payment['id'], entity_id)" in b

def test_v372_partial_and_grouped_reconciliations_keep_one_accounting_source_per_payment():
    assert "generate_sale_partial_payment_entry(c,inv,payment)" in BANK
    assert "generate_purchase_partial_payment_entry(c,p,payment)" in BANK
    assert "bank_invoice_allocations" in BANK
    assert "bank_purchase_allocations" in BANK

def test_v372_bank_fee_entry_is_balanced_627_512_and_entity_scoped():
    b=BANK.split("def banking_transaction_book_fee",1)[1].split("def banking_transaction_ignore",1)[0]
    assert "source_type='bank_fee'" in b
    assert "expense['code']" in b and "residual,0.0" in b
    assert "bank_account['code']" in b and "0.0,residual" in b
    assert "WHERE entity_id IS ? AND source_type='bank_fee' AND source_id=?" in b

def test_v372_reconciliation_is_atomic_until_commit():
    customer=BANK.split("def banking_reconcile",1)[1].split("def banking_sync",1)[0]
    supplier=BANK.split("def confirm_purchase_reconciliation",1)[1].split("def banking_transaction_book_fee",1)[0]
    for block in (customer,supplier):
        assert "c.commit()" in block
        assert "c.rollback()" in block
    assert customer.index("generate_sale_partial_payment_entry") < customer.index("c.commit()")
    assert supplier.index("generate_purchase_partial_payment_entry") < supplier.index("c.commit()")

def test_v372_fec_exports_accounting_entries_and_lines_entity_by_entity():
    b=ACC.split("def generate_fec(",1)[1].split("def fec_filename",1)[0]
    assert "FROM accounting_entries e" in b
    assert "FROM accounting_entry_lines l" in b
    assert "e.entity_id=?" in b
    assert "e.entity_id IS NULL" in b
    assert "_fec_amount(l['debit'])" in b
    assert "_fec_amount(l['credit'])" in b

def test_v372_fec_contains_bank_journal_entries_without_source_filtering():
    b=ACC.split("def generate_fec(",1)[1].split("def fec_filename",1)[0]
    assert "e.source_type" not in b
    assert "JOIN accounting_journals j ON j.code = e.journal_code" in b
    # Therefore BQ entries generated by bank reconciliation and bank fees
    # are exported when they fall in the requested entity/date range.
