from pathlib import Path
from jinja2 import Environment

ROOT = Path(__file__).resolve().parents[1]
B = (ROOT / "profitos/routes/bank_sync.py").read_text(encoding="utf-8")
T = (ROOT / "templates/banking.html").read_text(encoding="utf-8")


def test_template_parses():
    Environment().parse(T)


def test_progressive_automation_threshold_is_conservative():
    assert "confirmations >= 4 and score >= 90" in B
    assert "source == 'directionnelle'" in B


def test_progressive_automation_is_exposed_to_ui():
    assert "sug.automation_eligible" in T
    assert "Valider en 1 clic" in T


def test_conflicting_habits_are_blocked():
    assert "Habitudes contradictoires : aucune proposition automatique" in B


def test_ui_keeps_explicit_user_confirmation():
    assert "Habitude stable : catégorie, compte et TVA préremplis. Vérifiez puis validez en 1 clic." in T
    assert "Validation humaine requise." in T
    assert 'method="post"' in T
    # The button text is generated by a Jinja conditional in v386.
    assert "{% if sug and sug.automation_eligible %}Valider en 1 clic{% else %}Valider{% endif %}" in T
